### ISSUE TITLE
Monitor View Tree Server's JNDI Return 'Unexpected Error Response Service Unavailable'

### ISSUE THREAD

**Issue by tezhao-test** [oracle/weblogic-remote-console#47]
Platform: Windows 10
Version: 2.4.4
Weblogic version: 12.2.1.4.0
Ext version: 4.0
Reproduce Step:
Click Monitor View Tree-> Servers->Ex: AdminServer->JNDI, will get below exception stack 

<2023-5-25 下午03时14分24,419秒 CST> <Error> <REST> <BEA-2159702> <REST encountered the following error: java.net.SocketException: Permission denied: no further information>
<2023-5-25 下午03时14分24,421秒 CST> <Error> <REST> <BEA-2159702> <REST encountered the following error: java.net.SocketException: Permission denied: no further information
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
        at weblogic.socket.NIOSocketMuxer.newSocket(NIOSocketMuxer.java:453)
        at weblogic.socket.NIOSocketMuxer.newSocket(NIOSocketMuxer.java:364)
        at weblogic.socket.ChannelSocketFactory.createSocket(ChannelSocketFactory.java:98)
        at weblogic.socket.ChannelSocketFactory.createSocket(ChannelSocketFactory.java:58)
        at weblogic.net.http.HttpClient.openServer(HttpClient.java:394)
        at weblogic.net.http.HttpClient.openServer(HttpClient.java:513)
        at weblogic.net.http.HttpClient.New(HttpClient.java:315)
        at weblogic.net.http.HttpURLConnection.getHttpClient(HttpURLConnection.java:383)
        at weblogic.net.http.HttpURLConnection.getInputStream(HttpURLConnection.java:829)
        at weblogic.net.http.SOAPHttpURLConnection.getInputStream(SOAPHttpURLConnection.java:42)
        at weblogic.net.http.HttpURLConnection.getResponseCode(HttpURLConnection.java:1616)
        at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:394)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
        at weblogic.management.rest.lib.bean.utils.RestInvoker$RestInvokerWorker.invokeMethod(RestInvoker.java:379)
        at weblogic.management.rest.lib.bean.utils.RestInvoker$RestInvokerWorker.method(RestInvoker.java:277)
        at weblogic.management.rest.lib.bean.utils.RestInvoker$RestInvokerWorker.doNonResilientWork(RestInvoker.java:246)
        at weblogic.management.rest.lib.bean.utils.RestInvoker$RestInvokerWorker.access$300(RestInvoker.java:221)
        at weblogic.management.rest.lib.bean.utils.RestInvoker.methodEntity(RestInvoker.java:206)
        at weblogic.management.rest.lib.bean.utils.RestInvoker.methodJson(RestInvoker.java:173)
        at weblogic.management.rest.lib.bean.utils.RestInvoker.methodJson(RestInvoker.java:169)
        at weblogic.management.rest.lib.bean.utils.RestInvoker.get(RestInvoker.java:112)
        at weblogic.management.rest.lib.bean.utils.RestInvoker.get(RestInvoker.java:106)
        at weblogic.management.rest.lib.bean.utils.RestInvoker.get(RestInvoker.java:103)
        at weblogic.console.wls.rest.extension.jndi.resources.JNDIServerResource.getServerAdministrationUrl(JNDIServerResource.java:74)
        at weblogic.console.wls.rest.extension.jndi.resources.JNDIServerResource.getInitialContext(JNDIServerResource.java:56)
        at weblogic.console.wls.rest.extension.jndi.resources.JNDIServerResource.getJNDITree(JNDIServerResource.java:50)
        at weblogic.console.wls.rest.extension.jndi.resources.JNDIServerResource.getModel(JNDIServerResource.java:44)
        at weblogic.management.rest.lib.bean.resources.AbstractCustomCollectionChildResource.getRB(AbstractCustomCollectionChildResource.java:31)
        at weblogic.management.rest.lib.bean.resources.AbstractCustomCollectionChildResource._get(AbstractCustomCollectionChildResource.java:21)
        at weblogic.management.rest.lib.bean.resources.BaseResource.get(BaseResource.java:71)
        at weblogic.management.rest.lib.bean.resources.CustomCollectionChildResource.jaxrsGet(CustomCollectionChildResource.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:295)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
        at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:353)
        at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
        at weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:32)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3797)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3763)
        at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:344)
        at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
        at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
        at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
        at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2451)
        at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2299)
        at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2277)
        at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1720)
        at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1680)
        at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272)
        at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
        at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
        at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
        at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
        at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:655)
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
        at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)
>
<2023-5-25 下午03时14分24,424秒 CST> <Error> <REST> <BEA-2159702> <REST encountered the following error:
java.lang.Thread.getStackTrace(Thread.java:1564)
org.glassfish.admin.rest.utils.ExceptionUtil.log(ExceptionUtil.java:106)
org.glassfish.admin.rest.utils.ExceptionUtil.log(ExceptionUtil.java:77)
org.glassfish.admin.rest.utils.ExceptionUtil.log(ExceptionUtil.java:99)
weblogic.management.rest.utils.ExceptionMapper.toResponse(ExceptionMapper.java:41)
weblogic.management.rest.utils.ExceptionMapper.toResponse(ExceptionMapper.java:16)
org.glassfish.jersey.server.ServerRuntime$Responder.mapException(ServerRuntime.java:601)
org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:476)
org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:334)
org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
org.glassfish.jersey.internal.Errors.process(Errors.java:315)
org.glassfish.jersey.internal.Errors.process(Errors.java:297)
org.glassfish.jersey.internal.Errors.process(Errors.java:267)
org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:295)
weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:353)
weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:32)
weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3797)
weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3763)
weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:344)
weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2451)
weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2299)
weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2277)
weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1720)
weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1680)
weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272)
weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:655)
weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
weblogic.work.ExecuteThread.run(ExecuteThread.java:360)>
<2023-5-25 下午03时14分24,425秒 CST> <Error> <REST> <BEA-2159702> <REST encountered the following error:
Request
uri=/management/weblogic/12.2.1.0.0/domainRuntime/JNDI/AdminServer
method=GET>
<2023-5-25 下午03时14分24,426秒 CST> <Error> <REST> <BEA-2159702> <REST encountered the following error:
Response
uri=http://localhost:7001/management/weblogic/12.2.1.0.0/domainRuntime/JNDI/AdminServer?internal=true&expandedValues=false&enableConsoleRestExtension=true
method=GET
duration=261 ms
status=500
res headers={Content-Type=[application/json], Vary=[Accept-Encoding]}
res body={
  "status": 500,
  "type": "http:\/\/www.w3.org\/Protocols\/rfc2616\/rfc2616-sec10.html#sec10.4.1",
  "title": "FAILURE",
  "detail": "java.net.SocketException: Permission denied: no further information"
}
req headers={X-Requested-By=[ConsoleBackendRestClient], Content-type=[application/json], weblogic.edit.session=[default], X-Skip-Resource-Links=[true], Accept=[application/json], Authorization=[Basic d2VibG9naWM6MTIzNDU2Nzg=], User-Agent=[Jersey/2.35 (HttpUrlConnection 19.0.2)], Host=[localhost:7001], Connection=[keep-alive]}
req body=null>

**Comment by tezhao-test** [comment]
Version: 2.4.4
Platform:Windows 10

**Comment by tezhao-test** [comment]
self resolved
